### ISSUE TITLE
ServiceLoader is not instantiating the command handler classes

### ISSUE THREAD

**Issue by tcheeric** [tcheeric/nostr-java#147]
@guilhermegps 

While trying to implement NIP-42, I noticed some limitations with the current code.

NIP-42 expects the client to reply with a signed auth event when receiving an AUTH-message from a relay. Currently, this takes place in the onAuth method [here](https://github.com/tcheeric/nostr-java/blob/main/nostr-java-ws-handler-command-provider/src/main/java/nostr/ws/handler/command/provider/DefaultCommandHandler.java). 

However, to sign the event, you need to have access to the private key, which is not available in that class at the moment.

I have therefore introduced the concept of Context classes, where I store contextual information, including the private key. The context is created in the api module when instantiating a client object, passed along to the other modules, and is now available in the OnAuth command handler.

Additional major changes  (Branch 0.6-SNAPSHOT):
1. I noticed that for every request to a relay, we would open a new connection. This is not good. I have now created a ConnectionPool to keep track of the connections, and ensure that we only have one connection per relay.
2. One other change I have made is that I now have, for each relay command, e.g. Ok, Eose, Auth, Closed etc, a separate handler class, instead of a unique command handler class with a method for each command.
3. You will notice I have also renamed, added, removed a few modules. Hopefully this is more intuitive and cleaner.
4. etc.

**I welcome your opinions and suggestions on this.**

NOW, the Problem I am facing, is that the ServiceLoader is not instantiating the handler classes (See [here](https://github.com/tcheeric/nostr-java/blob/a7e61125e22b326f5f62043cb9c88896d47380d7/nostr-java-controller/src/main/java/nostr/controller/impl/ApplicationControllerImpl.java#L76)).

**I need a second pair of eyes to review and hopefully find what is missing, and why it's not working.**

Could you please have a look when you have a moment?

Thanks!

**Comment by guilhermegps** [comment]
Ok, I will take a look and answer you soon.

**Comment by guilhermegps** [comment]
I'd like to simulate your problem here. How can I do this? 

What is the test that you are trying?

What is the branch that I need to look? 0.6-SNAPSHOT ?

About your points:

1. Nice, good change. This is a really problem that we have.

2. Agree

3. I'd like to say that we need to have caution with the module changes, because this kind of change could broke application that is using an oldest version and decide to upgrade for this new version. Said it, I need to agree that modules more intuitive are better.

**Comment by tcheeric** [comment]
When you receive a message from a relay (ok, eose, notice etc) we use the service locator to instantiate the corresponding command handler class (default or custom) and run its handle method. This doesn't work, the service locator doesn't find the handler classes. This is what I'm struggling with at the moment. It seems so obvious but I can't find where the problem is. 

Agree re. caution with module changes but I saw these modifications as necessary. For clients, this would hopefully not be too much to change, just a bit of refactoring, changing their custom handlers, and create separate classes for each instead. 

Thanks.

**Comment by guilhermegps** [comment]
@tcheeric 

I found a problem with [this change](https://github.com/tcheeric/nostr-java/commit/e9e2b4fd9f185bb81af7c92bf93e14d1cf110994#diff-a6fafdb06bc9a30d2ade47dfb2f08d4142de1f8501bf87be9000978cb206e57dR127), the example of "filters"  broke, it's not necessary to sign a request for search events, they are public.

**Comment by guilhermegps** [comment]
Well, I'm getting a problem when try to connect with relays. When happened any problem during the connection with relay, I get an error [here](https://github.com/tcheeric/nostr-java/blob/feature/0.6-SNAPSHOT/nostr-java-util/src/main/java/nostr/util/thread/ThreadUtil.java#L51)  and all connections with all relays stop and no event is sent.


```
abr. 20, 2024 11:03:41 AM jdk.internal.net.http.HttpClientImpl$SelectorManager run
FINE: [HttpClient-1-SelectorManager] [96ms] HttpClientImpl(1) Next deadline is 3000
abr. 20, 2024 11:03:41 AM nostr.examples.NostrApiExamples lambda$0
SEVERE: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Failed to connect to Relay(uri=nostr.zebedee.cloud)
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Failed to connect to Relay(uri=nostr.zebedee.cloud)
	at nostr.util/nostr.util.thread.ThreadUtil.run(ThreadUtil.java:51)
	at nostr.client/nostr.client.Client.connect(Client.java:52)
	at nostr.api/nostr.api.Nostr.send(Nostr.java:145)
	at nostr.api/nostr.api.Nostr.send(Nostr.java:113)
	at nostr.api/nostr.api.EventNostr.send(EventNostr.java:46)
	at nostr.examples/nostr.examples.NostrApiExamples.sendTextNoteEvent(NostrApiExamples.java:196)
	at nostr.examples/nostr.examples.NostrApiExamples.lambda$0(NostrApiExamples.java:99)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Failed to connect to Relay(uri=nostr.zebedee.cloud)
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:205)
	at nostr.util/nostr.util.thread.ThreadUtil.run(ThreadUtil.java:48)
	... 11 more
Caused by: java.lang.RuntimeException: Failed to connect to Relay(uri=nostr.zebedee.cloud)
	at nostr.connection/nostr.connection.impl.ConnectionImpl.connect(ConnectionImpl.java:60)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at nostr.connection/nostr.connection.impl.ConnectionPool.connect(ConnectionPool.java:40)
	at nostr.client/nostr.client.Client$RelayConnectionTask.execute(Client.java:90)
	at nostr.client/nostr.client.Client$RelayConnectionTask.execute(Client.java:1)
	at nostr.util/nostr.util.thread.ThreadUtil.lambda$0(ThreadUtil.java:42)
	... 5 more

abr. 20, 2024 11:03:41 AM nostr.examples.NostrApiExamples main
FINE: ================== The End
```

**Comment by tcheeric** [comment]
> @tcheeric
> 
> I found a problem with [this change](https://github.com/tcheeric/nostr-java/commit/e9e2b4fd9f185bb81af7c92bf93e14d1cf110994#diff-a6fafdb06bc9a30d2ade47dfb2f08d4142de1f8501bf87be9000978cb206e57dR127), the example of "filters" broke, it's not necessary to sign a request for search events, they are public.

Yes, correct.

**Comment by guilhermegps** [comment]
> > @tcheeric
> > I found a problem with [this change](https://github.com/tcheeric/nostr-java/commit/e9e2b4fd9f185bb81af7c92bf93e14d1cf110994#diff-a6fafdb06bc9a30d2ade47dfb2f08d4142de1f8501bf87be9000978cb206e57dR127), the example of "filters" broke, it's not necessary to sign a request for search events, they are public.
> 
> Yes, correct.

So, I will let you check this problem and fix it.

You can test it [with this example](https://github.com/tcheeric/nostr-java/blob/feature/0.6-SNAPSHOT/nostr-java-examples/src/main/java/nostr/examples/NostrApiExamples.java#L293).

**Comment by guilhermegps** [comment]
> NOW, the Problem I am facing, is that the ServiceLoader is not instantiating the handler classes (See [here](https://github.com/tcheeric/nostr-java/blob/a7e61125e22b326f5f62043cb9c88896d47380d7/nostr-java-controller/src/main/java/nostr/controller/impl/ApplicationControllerImpl.java#L76)).

About this problem, I observed that you instanced the listener in [ConnectionImpl](https://github.com/tcheeric/nostr-java/blob/feature/0.6-SNAPSHOT/nostr-java-connection/src/main/java/nostr/connection/impl/ConnectionImpl.java#L49) as an OpenListener, but how the WebSocket will know when call TextListener, CloseListener or whatever? It's not clear for me. I did a teste and got sucess just changed OpenListener to TextListener.

Log:

```
abr. 21, 2024 12:14:32 PM jdk.internal.net.http.HttpClientImpl$SelectorManager run
FINE: [HttpClient-1-SelectorManager] [15s 778ms] HttpClientImpl(1) Next deadline is 3000
abr. 21, 2024 12:14:34 PM nostr.connection.impl.WebsocketClientListeners$TextListener handleReceivedText
INFO: Received message ["OK","6d83330b8d77b5868589f247015f658da1a95eed93f5d817b486cc9ee07cfa22",true,""] from Relay(uri=nostr.mom)
abr. 21, 2024 12:14:34 PM nostr.connection.impl.WebsocketClientListeners$TextListener handleReceivedText
INFO: Creating the command context with message OkMessage(eventId=6d83330b8d77b5868589f247015f658da1a95eed93f5d817b486cc9ee07cfa22, flag=true, message=)
abr. 21, 2024 12:14:34 PM jdk.internal.net.http.websocket.WebSocketImpl$ReceiveTask processText
FINE: [HttpClient-1-Worker-0] [18s 383ms] [WebSocket] exit onText 2 returned java.util.concurrent.CompletableFuture@279f774e[Completed exceptionally: java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "nostr.context.impl.DefaultRequestContext.getPrivateKey()" because "this.context" is null]
abr. 21, 2024 12:14:34 PM jdk.internal.net.http.websocket.WebSocketImpl tryChangeState
FINE: [HttpClient-1-Worker-0] [18s 383ms] [WebSocket] change state from TEXT to IDLE true
abr. 21, 2024 12:14:34 PM jdk.internal.net.http.websocket.WebSocketImpl$ReceiveTask run
FINE: [HttpClient-1-Worker-0] [18s 383ms] [WebSocket] receive state: IDLE
abr. 21, 2024 12:14:34 PM jdk.internal.net.http.websocket.WebSocketImpl tryChangeState
FINE: [HttpClient-1-Worker-0] [18s 383ms] [WebSocket] change state from IDLE to WAITING true
abr. 21, 2024 12:14:34 PM jdk.internal.net.http.websocket.TransportImpl request
```

**Comment by guilhermegps** [comment]
I observed either that the pool of connection is a little unstable. Maybe it was caused by the timeout, I don't know, but some times no connections are successfully established. We need to analyze carefully this pool and to be right that it's know under of control.

**Comment by tcheeric** [comment]
> > > @tcheeric
> > > I found a problem with [this change](https://github.com/tcheeric/nostr-java/commit/e9e2b4fd9f185bb81af7c92bf93e14d1cf110994#diff-a6fafdb06bc9a30d2ade47dfb2f08d4142de1f8501bf87be9000978cb206e57dR127), the example of "filters" broke, it's not necessary to sign a request for search events, they are public.
> > 
> > 
> > Yes, correct.
> 
> So, I will let you check this problem and fix it.
> 
> You can test it [with this example](https://github.com/tcheeric/nostr-java/blob/feature/0.6-SNAPSHOT/nostr-java-examples/src/main/java/nostr/examples/NostrApiExamples.java#L293).

Alright, will do.

**Comment by tcheeric** [comment]
> > NOW, the Problem I am facing, is that the ServiceLoader is not instantiating the handler classes (See [here](https://github.com/tcheeric/nostr-java/blob/a7e61125e22b326f5f62043cb9c88896d47380d7/nostr-java-controller/src/main/java/nostr/controller/impl/ApplicationControllerImpl.java#L76)).
> 
> About this problem, I observed that you instanced the listener in [ConnectionImpl](https://github.com/tcheeric/nostr-java/blob/feature/0.6-SNAPSHOT/nostr-java-connection/src/main/java/nostr/connection/impl/ConnectionImpl.java#L49) as an OpenListener, but how the WebSocket will know when call TextListener, CloseListener or whatever? It's not clear for me. I did a test and got success just changing OpenListener to TextListener.
> 
> Log:
> 
> ```
> abr. 21, 2024 12:14:32 PM jdk.internal.net.http.HttpClientImpl$SelectorManager run
> FINE: [HttpClient-1-SelectorManager] [15s 778ms] HttpClientImpl(1) Next deadline is 3000
> abr. 21, 2024 12:14:34 PM nostr.connection.impl.WebsocketClientListeners$TextListener handleReceivedText
> INFO: Received message ["OK","6d83330b8d77b5868589f247015f658da1a95eed93f5d817b486cc9ee07cfa22",true,""] from Relay(uri=nostr.mom)
> abr. 21, 2024 12:14:34 PM nostr.connection.impl.WebsocketClientListeners$TextListener handleReceivedText
> INFO: Creating the command context with message OkMessage(eventId=6d83330b8d77b5868589f247015f658da1a95eed93f5d817b486cc9ee07cfa22, flag=true, message=)
> abr. 21, 2024 12:14:34 PM jdk.internal.net.http.websocket.WebSocketImpl$ReceiveTask processText
> FINE: [HttpClient-1-Worker-0] [18s 383ms] [WebSocket] exit onText 2 returned java.util.concurrent.CompletableFuture@279f774e[Completed exceptionally: java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "nostr.context.impl.DefaultRequestContext.getPrivateKey()" because "this.context" is null]
> abr. 21, 2024 12:14:34 PM jdk.internal.net.http.websocket.WebSocketImpl tryChangeState
> FINE: [HttpClient-1-Worker-0] [18s 383ms] [WebSocket] change state from TEXT to IDLE true
> abr. 21, 2024 12:14:34 PM jdk.internal.net.http.websocket.WebSocketImpl$ReceiveTask run
> FINE: [HttpClient-1-Worker-0] [18s 383ms] [WebSocket] receive state: IDLE
> abr. 21, 2024 12:14:34 PM jdk.internal.net.http.websocket.WebSocketImpl tryChangeState
> FINE: [HttpClient-1-Worker-0] [18s 383ms] [WebSocket] change state from IDLE to WAITING true
> abr. 21, 2024 12:14:34 PM jdk.internal.net.http.websocket.TransportImpl request
> ```

I have found a solution. Look at how I use the CompositeListener to pass all listeners.
Also, in the ConnectionImpl, I was throwing an exception in the connect when the connection was failing. This is what, I believe, was causing all subsequent connection attempts to fail. I have now removed the throwing of the RuntimeException and I am logging an exception instead. This seems to work.

A COUPLE OF THINGS that I forgot to mention:

1. You have surely seen that I am not using the jetty library anymore to handle ws connections
2. Also, please always add the URI scheme of the relay in the properties file, e.g. ```ws://localhost:3333``` - Although I think probing for https and http is necessary, I don't think it should be handled in here, but at client level. I want to move away from it, also, in the spirit of simplifying things.


NOW, with these issues solved, my original problem should now become apparent: the ServiceLoader does not instantiate the command handlers (ok, eose, auth etc.)

**Comment by tcheeric** [comment]
I have finally found the issue with the ServiceLoader!
