### ISSUE TITLE
java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because the return value of "java.net.URI.getScheme()" is null

### ISSUE THREAD

**Issue by tcheeric** [tcheeric/nostr-java#18]
Apr 06, 2023 2:43:59 AM nostr.id.Client updateRelayInformation
SEVERE: null
java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because the return value of "java.net.URI.getScheme()" is null
	at nostr.ws.Connection.connect(Connection.java:114)
	at nostr.ws.Connection.<init>(Connection.java:68)
	at nostr.id.Client.updateRelayInformation(Client.java:142)
	at nostr.id.Client.openRelay(Client.java:117)
	at nostr.id.Client.lambda$init$4(Client.java:126)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by tcheeric** [comment]
In the configuration file, prefix the relay hostname with "wss://"

**Comment by tcheeric** [comment]
My comment here above is actually wrong.
The changes should be available on the develop branch.
