### ISSUE TITLE
The java.util.NoSuchElementException occurs in the constructor of ResponseHandlerImpl.

### ISSUE THREAD

**Issue by Memory-of-Snow** [tcheeric/nostr-java#35]
**Describe the bug**
The java.util.NoSuchElementException occurs in the constructor of ResponseHandlerImpl.

**To Reproduce**
1. Run NostrExamples.
2.An exception occurs on the line 68 "private final static Client CLIENT = Client.getInstance(RELAYS);"

**Expected behavior**
The exception does not occur.

**Additional context**
Is it correct to have the expression "filter(ch -> !ch.getClass().isAnnotationPresent(DefaultHandler.class))" inside the constructor of ResponseHandlerImpl? Shouldn't it be "filter(ch -> ch.getClass().isAnnotationPresent(DefaultHandler.class))" instead?

**Comment by tcheeric** [comment]
Please let me know if the issue persists in the feature/feature_bug_fixes branch

**Comment by Memory-of-Snow** [comment]
This bug has not been fixed even in the bugfix branch.

**Comment by tcheeric** [comment]
OK, I understand.
The idea is that your client should implement a custom ICommandHandler. See how I am doing here: https://github.com/tcheeric/nostr-bot/blob/feature/feature_bug_fixes/nostr-bot-core/src/main/java/nostr/bot/core/command/handler/provider/BotCommandHandler.java

But you are right too, I still need to catch this exception and use the default handler provided in nostr-java when no custom handler is provided.

**Comment by tcheeric** [comment]
Can you update your constructor to this and try again:

```
    public ResponseHandlerImpl() {

        try {
            this.commandHandler = ServiceLoader
                    .load(ICommandHandler.class).stream().map(p -> p.get())
                    .filter(ch -> !ch.getClass().isAnnotationPresent(DefaultHandler.class))
                    .findFirst()
                    .get();
        } catch (NoSuchElementException ex) {
            log.log(Level.WARNING, "No custom command handler provided. Using default command handler");
            this.commandHandler = ServiceLoader
                    .load(ICommandHandler.class).stream().map(p -> p.get())
                    .filter(ch -> ch.getClass().isAnnotationPresent(DefaultHandler.class))
                    .findFirst()
                    .get();
        }
    }

```

Also, make sure to make commandHandler **non**-final.

**Comment by tcheeric** [comment]
I have applied the above change and pushed to the branch

**Comment by Memory-of-Snow** [comment]
I am still experiencing an exception.

log
```
6月 15, 2023 7:52:28 午後 nostr.ws.Connection serverURI
情報: Openning a secure connection to nostr.h3z.jp
6月 15, 2023 7:52:28 午後 nostr.ws.Connection serverURI
情報: Openning a secure connection to nostr.fediverse.jp
6月 15, 2023 7:52:28 午後 nostr.ws.Connection serverURI
情報: Openning a secure connection to nostr-relay.nokotaro.com
6月 15, 2023 7:52:28 午後 nostr.ws.Connection serverURI
情報: Openning a secure connection to yabu.me
6月 15, 2023 7:52:28 午後 nostr.ws.Connection serverURI
情報: Openning a secure connection to nostr.holybea.com
6月 15, 2023 7:52:28 午後 nostr.ws.Connection serverURI
情報: Openning a secure connection to relay-jp.nostr.wirednet.jp
6月 15, 2023 7:52:28 午後 nostr.ws.response.handler.provider.ResponseHandlerImpl <init>
警告: No custom command handler provided. Using default command handler
6月 15, 2023 7:52:28 午後 nostr.ws.response.handler.provider.ResponseHandlerImpl <init>
警告: No custom command handler provided. Using default command handler
6月 15, 2023 7:52:28 午後 nostr.ws.response.handler.provider.ResponseHandlerImpl <init>
警告: No custom command handler provided. Using default command handler
6月 15, 2023 7:52:28 午後 nostr.id.Client updateRelayInformation
重大: null
java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.get(Optional.java:143)
	at nostr.ws.response.handler.provider/nostr.ws.response.handler.provider.ResponseHandlerImpl.<init>(ResponseHandlerImpl.java:45)
	at nostr.ws/nostr.ws.ClientListenerEndPoint.<init>(ClientListenerEndPoint.java:33)
	at nostr.ws/nostr.ws.Connection.connect(Connection.java:110)
	at nostr.ws/nostr.ws.Connection.<init>(Connection.java:60)
	at nostr.id/nostr.id.Client.updateRelayInformation(Client.java:193)
	at nostr.id/nostr.id.Client.openRelay(Client.java:166)
	at nostr.id/nostr.id.Client.openRelay(Client.java:162)
	at nostr.id/nostr.id.Client.lambda$init$5(Client.java:174)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

6月 15, 2023 7:52:28 午後 nostr.id.Client updateRelayInformation
重大: null
java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.get(Optional.java:143)
	at nostr.ws.response.handler.provider/nostr.ws.response.handler.provider.ResponseHandlerImpl.<init>(ResponseHandlerImpl.java:45)
	at nostr.ws/nostr.ws.ClientListenerEndPoint.<init>(ClientListenerEndPoint.java:33)
	at nostr.ws/nostr.ws.Connection.connect(Connection.java:110)
	at nostr.ws/nostr.ws.Connection.<init>(Connection.java:60)
	at nostr.id/nostr.id.Client.updateRelayInformation(Client.java:193)
	at nostr.id/nostr.id.Client.openRelay(Client.java:166)
	at nostr.id/nostr.id.Client.openRelay(Client.java:162)
	at nostr.id/nostr.id.Client.lambda$init$5(Client.java:174)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

6月 15, 2023 7:52:28 午後 nostr.id.Client openRelay
普通: Relay connected: Relay(uri=wss://nostr-relay.nokotaro.com)
6月 15, 2023 7:52:28 午後 nostr.id.Client updateRelayInformation
重大: null
java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.get(Optional.java:143)
	at nostr.ws.response.handler.provider/nostr.ws.response.handler.provider.ResponseHandlerImpl.<init>(ResponseHandlerImpl.java:45)
	at nostr.ws/nostr.ws.ClientListenerEndPoint.<init>(ClientListenerEndPoint.java:33)
	at nostr.ws/nostr.ws.Connection.connect(Connection.java:110)
	at nostr.ws/nostr.ws.Connection.<init>(Connection.java:60)
	at nostr.id/nostr.id.Client.updateRelayInformation(Client.java:193)
	at nostr.id/nostr.id.Client.openRelay(Client.java:166)
	at nostr.id/nostr.id.Client.openRelay(Client.java:162)
	at nostr.id/nostr.id.Client.lambda$init$5(Client.java:174)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

6月 15, 2023 7:52:28 午後 nostr.ws.response.handler.provider.ResponseHandlerImpl <init>
警告: No custom command handler provided. Using default command handler
6月 15, 2023 7:52:28 午後 nostr.ws.response.handler.provider.ResponseHandlerImpl <init>
警告: No custom command handler provided. Using default command handler
6月 15, 2023 7:52:28 午後 nostr.ws.response.handler.provider.ResponseHandlerImpl <init>
警告: No custom command handler provided. Using default command handler
6月 15, 2023 7:52:28 午後 nostr.id.Client openRelay
普通: Relay connected: Relay(uri=wss://nostr.holybea.com)
6月 15, 2023 7:52:28 午後 nostr.id.Client updateRelayInformation
重大: null
java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.get(Optional.java:143)
	at nostr.ws.response.handler.provider/nostr.ws.response.handler.provider.ResponseHandlerImpl.<init>(ResponseHandlerImpl.java:45)
	at nostr.ws/nostr.ws.ClientListenerEndPoint.<init>(ClientListenerEndPoint.java:33)
	at nostr.ws/nostr.ws.Connection.connect(Connection.java:110)
	at nostr.ws/nostr.ws.Connection.<init>(Connection.java:60)
	at nostr.id/nostr.id.Client.updateRelayInformation(Client.java:193)
	at nostr.id/nostr.id.Client.openRelay(Client.java:166)
	at nostr.id/nostr.id.Client.openRelay(Client.java:162)
	at nostr.id/nostr.id.Client.lambda$init$5(Client.java:174)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

6月 15, 2023 7:52:28 午後 nostr.id.Client updateRelayInformation
重大: null
java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.get(Optional.java:143)
	at nostr.ws.response.handler.provider/nostr.ws.response.handler.provider.ResponseHandlerImpl.<init>(ResponseHandlerImpl.java:45)
	at nostr.ws/nostr.ws.ClientListenerEndPoint.<init>(ClientListenerEndPoint.java:33)
	at nostr.ws/nostr.ws.Connection.connect(Connection.java:110)
	at nostr.ws/nostr.ws.Connection.<init>(Connection.java:60)
	at nostr.id/nostr.id.Client.updateRelayInformation(Client.java:193)
	at nostr.id/nostr.id.Client.openRelay(Client.java:166)
	at nostr.id/nostr.id.Client.openRelay(Client.java:162)
	at nostr.id/nostr.id.Client.lambda$init$5(Client.java:174)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

6月 15, 2023 7:52:28 午後 nostr.id.Client updateRelayInformation
重大: null
java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.get(Optional.java:143)
	at nostr.ws.response.handler.provider/nostr.ws.response.handler.provider.ResponseHandlerImpl.<init>(ResponseHandlerImpl.java:45)
	at nostr.ws/nostr.ws.ClientListenerEndPoint.<init>(ClientListenerEndPoint.java:33)
	at nostr.ws/nostr.ws.Connection.connect(Connection.java:110)
	at nostr.ws/nostr.ws.Connection.<init>(Connection.java:60)
	at nostr.id/nostr.id.Client.updateRelayInformation(Client.java:193)
	at nostr.id/nostr.id.Client.openRelay(Client.java:166)
	at nostr.id/nostr.id.Client.openRelay(Client.java:162)
	at nostr.id/nostr.id.Client.lambda$init$5(Client.java:174)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

6月 15, 2023 7:52:28 午後 nostr.id.Client openRelay
普通: Relay connected: Relay(uri=wss://yabu.me)
6月 15, 2023 7:52:28 午後 nostr.id.Client openRelay
普通: Relay connected: Relay(uri=wss://nostr.h3z.jp)
6月 15, 2023 7:52:28 午後 nostr.id.Client openRelay
普通: Relay connected: Relay(uri=wss://nostr.fediverse.jp)
6月 15, 2023 7:52:28 午後 nostr.id.Client openRelay
普通: Relay connected: Relay(uri=wss://relay-jp.nostr.wirednet.jp)
6月 15, 2023 7:52:33 午後 nostr.examples.NostrExamples main
普通: ================= The Beginning
6月 15, 2023 7:52:33 午後 nostr.examples.NostrExamples logAccountsData
情報: ################################ ACCOUNTS BEGINNING ################################
*** RECEIVER ***

* PrivateKey: nsec12h84pe426mzpnk2y08anpstnjuuk92md860sqju6urr7xrkpjukqs3dqv3
* PrivateKey HEX: 55cf50e6aad6c419d94479fb30c173973962ab6d3e9f004b9ae0c7e30ec1972c
* PublicKey: npub1cf22t0twjqx2ns6ct2skyc3ztu7mhpgvtfsrc33l9zr7jzxvyqas0gh9wt
* PublicKey HEX: c254a5bd6e900ca9c3585aa16262225f3dbb850c5a603c463f2887e908cc203b

*** SENDER ***

* PrivateKey: nsec13v25elsajnp859jwvk444td8ugr4zhrusx78ycwd8z9t2hj47gwqfyy00p
* PrivateKey HEX: 8b154cfe1d94c27a164e65ab5aada7e207515c7c81bc7261cd388ab55e55f21c
* PublicKey: npub16f23sgqzcen6jvje8d3xx06szkvhtfl9e4d3fwv0msxzpeneqe9qjfu75n
* PublicKey HEX: d255182002c667a932593b62633f50159975a7e5cd5b14b98fdc0c20e679064a

################################ ACCOUNTS END ################################
##############################
##############################
	sendTextNoteEvent
###########################	metaDataEvent
##############################
###
6月 15, 2023 7:52:33 午後 nostr.id.Identity signEvent
詳細: Serialized event: [0,"d255182002c667a932593b62633f50159975a7e5cd5b14b98fdc0c20e679064a",1686826353,1,[["p","c254a5bd6e900ca9c3585aa16262225f3dbb850c5a603c463f2887e908cc203b"]],"nostr-java APIからの投稿テスト"]
6月 15, 2023 7:52:33 午後 nostr.examples.NostrExamples main
普通: ================== The End

プロセスは終了コード 0 で終了しました

```

**Comment by Memory-of-Snow** [comment]
P.S.
In my local environment, I am executing only the sendTextNoteEvent() and metaDataEvent() functions.

**Comment by tcheeric** [comment]
OK, makes sense. I'll fix this too later. 

Thanks
-- 
 Sent with Tutanota, enjoy secure & ad-free emails. 



15 Jun 2023, 11:54 by ***@***.***:

**Comment by tcheeric** [comment]
In this case, you might not need a custom handler, then. 
-- 
 Sent with Tutanota, enjoy secure & ad-free emails. 



15 Jun 2023, 11:57 by ***@***.***:

**Comment by Memory-of-Snow** [comment]
It seems that no services are being loaded with ServiceLoader.load(ICommandHandler.class).

**Comment by tcheeric** [comment]
Can you confirm you have the `nostr-java-ws-handler-command-provider` in your classpath? Your client should reference it in the pom. The module will expose the default command handler (DefaultCommandHandler.java)

**Comment by tcheeric** [comment]
I have added the missing reference to `nostr-java-ws-handler-command-provider` and I am not getting the error anymore. There are a few other errors I need to look into.

**Comment by Memory-of-Snow** [comment]
When will the "feature_bug_fies" branch, where the reference to "nostr-java-ws-handler-command-provider" was added, be updated? Alternatively, can we improve it immediately with the configuration in the Pom.xml or other means?

**Comment by tcheeric** [comment]
It should be working now. Fix pushed to branch

**Comment by Memory-of-Snow** [comment]
OK.I have confirmed that the NoSuchElementException is no longer occurring.

Thank you.

**Comment by tcheeric** [comment]
great, thanks!

-- 
 Sent with Tutanota, enjoy secure & ad-free emails. 



Jun 15, 2023, 22:26 by ***@***.***:
