### ISSUE TITLE
The parsing of List<String> failed from the message in ResponseHandlerImpl.java

### ISSUE THREAD

**Issue by Memory-of-Snow** [tcheeric/nostr-java#39]
**Describe the bug**
Even if the message is received successfully, parsing from the message to List<String> fails in ResponseHandlerImpl.

**Expected behavior**
The message to be parsed into a List<String>.

**Additional context**
The received message is a string surrounded by square brackets [], and it is not in JSON format, so it cannot be converted to String[] using objectMapper.readValue(message, String[].class).

**Comment by Memory-of-Snow** [comment]
I apologize for the previous error in the thread. The incoming message was in JSON format. However, it cannot be directly converted to a String[].

**Comment by Memory-of-Snow** [comment]
In my local environment, an error occurred in the constructor of ResponseHandlerImpl, preventing the creation of the object. Therefore, I have prepared separate test code.


```java
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.util.*;

public class JsonParseTest {

    private static final String parseTarget =
            "[\"EVENT\"," +
                    "\"npub17x6pn22ukq3n5yw5x9prksdyyu6ww9jle2ckpqwdprh3ey8qhe6stnpujh\"," +
                    "{" +
                    "\"content\":\"直んないわ。まあええか\"," +
                    "\"created_at\":1686199583," +
                    "\"id\":\"fc7f200c5bed175702bd06c7ca5dba90d3497e827350b42fc99c3a4fa276a712\"," +
                    "\"kind\":1," +
                    "\"pubkey\":\"8c59239319637f97e007dad0d681e65ce35b1ace333b629e2d33f9465c132608\"," +
                    "\"sig\":\"9584afd231c52fcbcec6ce668a2cc4b6dc9b4d9da20510dcb9005c6844679b4844edb7a2e1e0591958b0295241567c774dbf7d39a73932877542de1a5f963f4b\"," +
                    "\"tags\":[]" +
                    "}]";

    public static void main(String[] args){
        ObjectMapper objectMapper = new ObjectMapper();
        List<String> items =null;
        try {
            items = Arrays.asList(objectMapper.readValue(parseTarget, String[].class));
        } catch (JsonProcessingException e) {
            System.err.println("fail to parse.");
            e.printStackTrace();
            System.exit(-1000);
        }
        for (String str : items) {
            System.out.println("item="+str);
        }
    }
}
```

result:
```
fail to parse.
com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `[Ljava.lang.String;` from Object value (token `JsonToken.START_OBJECT`)
 at [Source: (String)"["EVENT","npub17x6pn22ukq3n5yw5x9prksdyyu6ww9jle2ckpqwdprh3ey8qhe6stnpujh",{"content":"直んないわ。まあええか","created_at":1686199583,"id":"fc7f200c5bed175702bd06c7ca5dba90d3497e827350b42fc99c3a4fa276a712","kind":1,"pubkey":"8c59239319637f97e007dad0d681e65ce35b1ace333b629e2d33f9465c132608","sig":"9584afd231c52fcbcec6ce668a2cc4b6dc9b4d9da20510dcb9005c6844679b4844edb7a2e1e0591958b0295241567c774dbf7d39a73932877542de1a5f963f4b","tags":[]}]"; line: 1, column: 76] (through reference chain: java.lang.Object[][2])
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1746)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1520)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1425)
	at com.fasterxml.jackson.databind.DeserializationContext.extractScalarFromObject(DeserializationContext.java:937)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer._parseString(StdDeserializer.java:1421)
	at com.fasterxml.jackson.databind.deser.std.StringArrayDeserializer.deserialize(StringArrayDeserializer.java:168)
	at com.fasterxml.jackson.databind.deser.std.StringArrayDeserializer.deserialize(StringArrayDeserializer.java:27)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4730)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3677)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3645)
	at io.github.memory_of_snow.main.JsonParseTest.main(JsonParseTest.java:28)

プロセスは終了コード -1000 で終了しました
```

It seems that an exception is occurring because the JSON contained within the EVENT message cannot be converted to a String.

**Comment by tcheeric** [comment]
Apologies for the late reply, but I am seeing this only now.
Can you test this against the changes pushed into the feature_bug_fixes branch?
I have attempted to fix all the (de)serialization issues.

**Comment by Memory-of-Snow** [comment]
The following is the test for the EVENTMessage section.

DebugBranchTest.java
```java
package io.github.memory_of_snow.main;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

public class DebugBranchTest {

    private static final String parseTarget =
            "[\"EVENT\"," +
                    "\"npub17x6pn22ukq3n5yw5x9prksdyyu6ww9jle2ckpqwdprh3ey8qhe6stnpujh\"," +
                    "{" +
                    "\"content\":\"直んないわ。まあええか\"," +
                    "\"created_at\":1686199583," +
                    "\"id\":\"fc7f200c5bed175702bd06c7ca5dba90d3497e827350b42fc99c3a4fa276a712\"," +
                    "\"kind\":1," +
                    "\"pubkey\":\"8c59239319637f97e007dad0d681e65ce35b1ace333b629e2d33f9465c132608\"," +
                    "\"sig\":\"9584afd231c52fcbcec6ce668a2cc4b6dc9b4d9da20510dcb9005c6844679b4844edb7a2e1e0591958b0295241567c774dbf7d39a73932877542de1a5f963f4b\"," +
                    "\"tags\":[]" +
                    "}]";

    public static void main(String[] args){
        Object[] items = unmarshall(parseTarget);
        final String command = items[0].toString();

        System.out.println("items size : "+ items.length);

        for (Object entry  : items) {
            System.out.println("item = " + entry.toString());
        }

        try {
            String jsonEvent = new ObjectMapper().writeValueAsString(items[2]);
            System.out.println("innerJson = " + jsonEvent);
        }catch (JsonProcessingException e) {
            e.printStackTrace();
            System.exit(-1000);
        }
    }

    private static Object[] unmarshall(String jsonString) {
        try {
            ObjectMapper mapper = new ObjectMapper();
            return mapper.readValue(jsonString, Object[].class);
        } catch (JsonProcessingException e) {
            throw new RuntimeException(e);
        }
    }

}
```
result
```
items size : 3
item = EVENT
item = npub17x6pn22ukq3n5yw5x9prksdyyu6ww9jle2ckpqwdprh3ey8qhe6stnpujh
item = {content=直んないわ。まあええか, created_at=1686199583, id=fc7f200c5bed175702bd06c7ca5dba90d3497e827350b42fc99c3a4fa276a712, kind=1, pubkey=8c59239319637f97e007dad0d681e65ce35b1ace333b629e2d33f9465c132608, sig=9584afd231c52fcbcec6ce668a2cc4b6dc9b4d9da20510dcb9005c6844679b4844edb7a2e1e0591958b0295241567c774dbf7d39a73932877542de1a5f963f4b, tags=[]}
innerJson = {"content":"直んないわ。まあええか","created_at":1686199583,"id":"fc7f200c5bed175702bd06c7ca5dba90d3497e827350b42fc99c3a4fa276a712","kind":1,"pubkey":"8c59239319637f97e007dad0d681e65ce35b1ace333b629e2d33f9465c132608","sig":"9584afd231c52fcbcec6ce668a2cc4b6dc9b4d9da20510dcb9005c6844679b4844edb7a2e1e0591958b0295241567c774dbf7d39a73932877542de1a5f963f4b","tags":[]}

プロセスは終了コード 0 で終了しました
```

When converted to an array of object types, the double quotation marks within the enclosed JSON are lost, but they seem to be added again when using writeValueAsString(). However, I have not tested this for nested tags or similar cases.

**Comment by tcheeric** [comment]
OK, I'll have a look as well

**Comment by tcheeric** [comment]
I have added JsonParseTest class in the nostr-java-test maven module for this issue. The test scenario is now successful. I will add more test cases this week-end

**Comment by tcheeric** [comment]
Test case passed.
